library(extrafont)

setwd("/home/fm/git/thesis/chapters/04-mobilenets/images")

embed_fonts("compare-maxinstances-block.pdf")
embed_fonts("R-virtualized-startstop-blocking-barchart.pdf")
embed_fonts("R-virtualized-startstop-tunnelusage-blocking-comparison.pdf")
embed_fonts("blocking-comparison.pdf")
embed_fonts("R-monolithic-tunnelusage.pdf")
embed_fonts("R-monolithic-blocking.pdf")
embed_fonts("R-virtualized-tunnelusage.pdf")
embed_fonts("R-virtualized-blocking.pdf")
embed_fonts("R-virtualized-instanceuse.pdf")
embed_fonts("R-virtualized-mean-instanceusage.pdf")

## unconverted files, try embed nontheless
embed_fonts("R-duration-timeofday-ecdf.pdf")
embed_fonts("R-IAT-successful-2h-ecdfs.pdf")
embed_fonts("R-IAT-fromflows-ecdfs-2h.pdf")
embed_fonts("R-IAT-fromflows-umts-ecdfs-2h.pdf")
embed_fonts("R-IAT-fromflows-gprs-ecdfs-2h.pdf")
embed_fonts("R-tunnel-duration-operating-system.pdf")
embed_fonts("R-tunnel-duration-device-type.pdf")
embed_fonts("R-createspersecond-1h-violin.pdf")
embed_fonts("create_freq.pdf")
embed_fonts("R-IAT-ecdfs.pdf")
embed_fonts("R-update-time-cdfs.pdf")
embed_fonts("R-IAT-active-fit-cdf-facets.pdf")
embed_fonts("timeslot-fits.pdf")
